apiVersion: v1
kind: Service
metadata:
  name: nodejs-express-hello-world-service
  labels:
    app: nodejs-express-hello-world
spec:
  type: LoadBalancer
  selector:
    app: nodejs-express-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
